### ISSUE TITLE
分区

### ISSUE THREAD

**Issue by rbce** [Tjyy-1223/DADS#2]
首先感谢您的代码分享，在尝试运行后有一个问题想要请教，以inceptionV2为例，DSL算法得到的分区边集合model_partition_edge的长度并不一定为4，但在InceptionBlockV2.py"文件中，assert len(model_partition_edge) == 4就会报错，该如何解决呢
python edge_api.py -i 172.17.4.209 -p 9999 -d cpu -t inception_v2
monitor client get latency : 3704.888750114464 MB/s 
short message , model type has been sent successfully
edge_latency_list : [107.84478958230466, 13.369368622079492, 26.299802120774984, 57.26995733566582, 7.406370993703604, 26.44088137894869, 42.77969708200544, 17.51779713667929, 26.273923716507852, 27.527293609455228, 8.349713776260614, 14.03235960751772, 11.371594085358083, 0.06040649022907019]
cloud_latency_list : [69.2196918418631, 13.138559181243181, 97.52658936195076, 87.32770101632923, 7.599794655106962, 37.64628728386015, 25.54533185902983, 23.401623335666955, 30.511609348468482, 2.8537589590996504, 3.5421702777966857, 3.650573710910976, 1.1728882789611816, 0.19014575518667698]
start construct graph for model...
graph_partition_edge : [('v9', 'v10'), ('v0', 'v1'), ('v5', 'v15')]
partition edges : [(9, 10), (0, 1), (5, 5)]
short message , partition strategy has been sent successfully
Traceback (most recent call last):
  File "/home/dzg/pwy/DADS-main/edge_api.py", line 70, in <module>
    start_client(ip, port, x, model_type, upload_bandwidth, device)
  File "/home/dzg/pwy/DADS-main/server_func.py", line 101, in start_client
    edge_model, _ = inference_utils.model_partition(model, model_partition_edge)
  File "/home/dzg/pwy/DADS-main/utils/inference_utils.py", line 271, in model_partition
    return construct_edge_cloud_inception_block(model, model_partition_edge)
  File "/home/dzg/pwy/DADS-main/models/InceptionBlockV2.py", line 265, in construct_edge_cloud_inception_block
    assert len(model_partition_edge) == 4
AssertionError

**Comment by rbce** [comment]
monitor client get latency : 3628.500302129017 MB/s 
short message , model type has been sent successfully
edge_latency_list : [63.43269697390497, 9.654833446256816, 44.83142872340977, 61.84244733303785, 12.866145744919777, 46.15169146563858, 27.649305388331413, 41.88336411025375, 31.388047221116725, 4.514111345633864, 51.484244177117944, 21.06482470408082, 39.01517842896283, 1.0354229947552085]
cloud_latency_list : [46.15126538556069, 14.422013889998198, 49.16963547002524, 76.33295739069581, 11.484189750626683, 53.29806129448116, 25.37192697636783, 38.356200186535716, 26.650104694999754, 37.58544276934117, 49.126882501877844, 4.261903907172382, 27.373381098732352, 0.7988788187503815]
start construct graph for model...
graph_partition_edge : [('v4', 'v5'), ('v6', 'v14'), ('v0', 'v1'), ('v10', 'v11')]
partition edges : [(4, 5), (6, 14), (0, 1), (10, 11)]
short message , partition strategy has been sent successfully
Traceback (most recent call last):
  File "/home/dzg/pwy/DADS-main/edge_api.py", line 70, in <module>
    start_client(ip, port, x, model_type, upload_bandwidth, device)
  File "/home/dzg/pwy/DADS-main/server_func.py", line 101, in start_client
    edge_model, _ = inference_utils.model_partition(model, model_partition_edge)
  File "/home/dzg/pwy/DADS-main/utils/inference_utils.py", line 271, in model_partition
    return construct_edge_cloud_inception_block(model, model_partition_edge)
  File "/home/dzg/pwy/DADS-main/models/InceptionBlockV2.py", line 290, in construct_edge_cloud_inception_block
    for layer in block:
TypeError: 'NoneType' object is not iterable
如果划分的边集长度为assert的4，也会出现空类型不可迭代的错误

**Comment by Tjyy-1223** [comment]
DADS这个框架的方法可以用来找到 构建图->找到最小割->找到最小割集中顶点对应的DNN层，但是如果涉及将模型进行划分，只能是根据模型所有可能的分层结构去自己调整，就像我在处理边集长度为4的情况一样。

但是：你的这个结果可能是云端推理速度比边端推理速度慢导致的吧，(0,1)这条边我记得是初始输入顶点到dnn层的第一个顶点的边，对这条边进行切分原理上讲已经将整个模型传输到云端推理了..不应该存在[('v4', 'v5'), ('v6', 'v14'), ('v0', 'v1'), ('v10', 'v11')]这种切分情况
